import { isNativeApp } from "./appbuild";

/**
 * Registers the app-shell service worker generated by vite-plugin-pwa.
 * Guards against registration in dev, preview, and iframe contexts where a
 * stale or conflicting worker would break the Lovable editor experience.
 */
export async function registerAppShellSW(): Promise<void> {
  if (typeof window === "undefined") return;
  if (!("serviceWorker" in navigator)) return;

  const hostname = window.location.hostname;
  const isDev = import.meta.env.DEV;
  const isPreview =
    hostname.startsWith("id-preview--") ||
    hostname.startsWith("preview--") ||
    hostname === "lovableproject.com" ||
    hostname.endsWith(".lovableproject.com") ||
    hostname === "lovableproject-dev.com" ||
    hostname.endsWith(".lovableproject-dev.com") ||
    hostname === "beta.lovable.dev" ||
    hostname.endsWith(".beta.lovable.dev");
  const isIframe = window.self !== window.top;
  const swOff = new URLSearchParams(window.location.search).has("sw");

  const matching = await navigator.serviceWorker.getRegistrations();
  const appShellRegs = matching.filter((r) => r.scope.endsWith("/") && r.active?.scriptURL?.includes("/sw.js"));

  if (isDev || isPreview || isIframe || swOff) {
    // Unregister any previously registered app-shell worker in these contexts.
    await Promise.all(appShellRegs.map((r) => r.unregister()));
    return;
  }

  // In the native app shell we still want offline caching, so register there too.
  if (appShellRegs.length > 0) return;

  try {
    await navigator.serviceWorker.register("/sw.js", { scope: "/" });
  } catch (err) {
    console.warn("[sw-register] failed to register app shell worker:", err);
  }
}
