/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as StoreOnboardingRouteImport } from './routes/store-onboarding'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HouseholdRouteImport } from './routes/household'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CouponsRouteImport } from './routes/coupons'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RecipesSlugRouteImport } from './routes/recipes.$slug'
import { Route as PortalStoresRouteImport } from './routes/portal.stores'
import { Route as PortalRewardsRouteImport } from './routes/portal.rewards'
import { Route as PortalPromotionsRouteImport } from './routes/portal.promotions'
import { Route as PortalProductsRouteImport } from './routes/portal.products'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalCouponsRouteImport } from './routes/portal.coupons'
import { Route as PortalCampaignsRouteImport } from './routes/portal.campaigns'
import { Route as PortalAnalyticsRouteImport } from './routes/portal.analytics'
import { Route as JoinSlugRouteImport } from './routes/join.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminVaultRouteImport } from './routes/admin.vault'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTaylorRouteImport } from './routes/admin.taylor'
import { Route as AdminStoresRouteImport } from './routes/admin.stores'
import { Route as AdminOrganisationsRouteImport } from './routes/admin.organisations'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai-usage'
import { Route as PortalStoresIndexRouteImport } from './routes/portal.stores.index'
import { Route as PortalStoresStoreIdRouteImport } from './routes/portal.stores.$storeId'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api/voice/speak'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreOnboardingRoute = StoreOnboardingRouteImport.update({
  id: '/store-onboarding',
  path: '/store-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdRoute = HouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsRoute = CouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RecipesSlugRoute = RecipesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecipesRoute,
} as any)
const PortalStoresRoute = PortalStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRewardsRoute = PortalRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPromotionsRoute = PortalPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProductsRoute = PortalProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCouponsRoute = PortalCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCampaignsRoute = PortalCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRoute,
} as any)
const JoinSlugRoute = JoinSlugRouteImport.update({
  id: '/join/$slug',
  path: '/join/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultRoute = AdminVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTaylorRoute = AdminTaylorRouteImport.update({
  id: '/taylor',
  path: '/taylor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganisationsRoute = AdminOrganisationsRouteImport.update({
  id: '/organisations',
  path: '/organisations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const PortalStoresIndexRoute = PortalStoresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalStoresRoute,
} as any)
const PortalStoresStoreIdRoute = PortalStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => PortalStoresRoute,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/household': typeof HouseholdRoute
  '/inbox': typeof InboxRoute
  '/lists': typeof ListsRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/store-onboarding': typeof StoreOnboardingRoute
  '/stores': typeof StoresRoute
  '/vision': typeof VisionRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/taylor': typeof AdminTaylorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$slug': typeof JoinSlugRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/coupons': typeof PortalCouponsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/stores': typeof PortalStoresRouteWithChildren
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/portal/stores/$storeId': typeof PortalStoresStoreIdRoute
  '/portal/stores/': typeof PortalStoresIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/household': typeof HouseholdRoute
  '/inbox': typeof InboxRoute
  '/lists': typeof ListsRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/store-onboarding': typeof StoreOnboardingRoute
  '/stores': typeof StoresRoute
  '/vision': typeof VisionRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/taylor': typeof AdminTaylorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$slug': typeof JoinSlugRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/coupons': typeof PortalCouponsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/portal/stores/$storeId': typeof PortalStoresStoreIdRoute
  '/portal/stores': typeof PortalStoresIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/coupons': typeof CouponsRoute
  '/deals': typeof DealsRoute
  '/household': typeof HouseholdRoute
  '/inbox': typeof InboxRoute
  '/lists': typeof ListsRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/pantry': typeof PantryRoute
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/store-onboarding': typeof StoreOnboardingRoute
  '/stores': typeof StoresRoute
  '/vision': typeof VisionRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/organisations': typeof AdminOrganisationsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/taylor': typeof AdminTaylorRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vault': typeof AdminVaultRoute
  '/api/chat': typeof ApiChatRoute
  '/join/$slug': typeof JoinSlugRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/campaigns': typeof PortalCampaignsRoute
  '/portal/coupons': typeof PortalCouponsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/products': typeof PortalProductsRoute
  '/portal/promotions': typeof PortalPromotionsRoute
  '/portal/rewards': typeof PortalRewardsRoute
  '/portal/stores': typeof PortalStoresRouteWithChildren
  '/recipes/$slug': typeof RecipesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
  '/portal/stores/$storeId': typeof PortalStoresStoreIdRoute
  '/portal/stores/': typeof PortalStoresIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/household'
    | '/inbox'
    | '/lists'
    | '/loyalty'
    | '/notifications'
    | '/onboarding'
    | '/pantry'
    | '/portal'
    | '/profile'
    | '/recipes'
    | '/settings'
    | '/store-onboarding'
    | '/stores'
    | '/vision'
    | '/admin/ai-usage'
    | '/admin/audit'
    | '/admin/knowledge'
    | '/admin/onboarding'
    | '/admin/organisations'
    | '/admin/stores'
    | '/admin/taylor'
    | '/admin/users'
    | '/admin/vault'
    | '/api/chat'
    | '/join/$slug'
    | '/portal/analytics'
    | '/portal/campaigns'
    | '/portal/coupons'
    | '/portal/messages'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/rewards'
    | '/portal/stores'
    | '/recipes/$slug'
    | '/admin/'
    | '/portal/'
    | '/recipes/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/portal/stores/$storeId'
    | '/portal/stores/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/household'
    | '/inbox'
    | '/lists'
    | '/loyalty'
    | '/notifications'
    | '/onboarding'
    | '/pantry'
    | '/profile'
    | '/settings'
    | '/store-onboarding'
    | '/stores'
    | '/vision'
    | '/admin/ai-usage'
    | '/admin/audit'
    | '/admin/knowledge'
    | '/admin/onboarding'
    | '/admin/organisations'
    | '/admin/stores'
    | '/admin/taylor'
    | '/admin/users'
    | '/admin/vault'
    | '/api/chat'
    | '/join/$slug'
    | '/portal/analytics'
    | '/portal/campaigns'
    | '/portal/coupons'
    | '/portal/messages'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/rewards'
    | '/recipes/$slug'
    | '/admin'
    | '/portal'
    | '/recipes'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/portal/stores/$storeId'
    | '/portal/stores'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/chat'
    | '/coupons'
    | '/deals'
    | '/household'
    | '/inbox'
    | '/lists'
    | '/loyalty'
    | '/notifications'
    | '/onboarding'
    | '/pantry'
    | '/portal'
    | '/profile'
    | '/recipes'
    | '/settings'
    | '/store-onboarding'
    | '/stores'
    | '/vision'
    | '/admin/ai-usage'
    | '/admin/audit'
    | '/admin/knowledge'
    | '/admin/onboarding'
    | '/admin/organisations'
    | '/admin/stores'
    | '/admin/taylor'
    | '/admin/users'
    | '/admin/vault'
    | '/api/chat'
    | '/join/$slug'
    | '/portal/analytics'
    | '/portal/campaigns'
    | '/portal/coupons'
    | '/portal/messages'
    | '/portal/products'
    | '/portal/promotions'
    | '/portal/rewards'
    | '/portal/stores'
    | '/recipes/$slug'
    | '/admin/'
    | '/portal/'
    | '/recipes/'
    | '/api/voice/speak'
    | '/api/voice/transcribe'
    | '/portal/stores/$storeId'
    | '/portal/stores/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CouponsRoute: typeof CouponsRoute
  DealsRoute: typeof DealsRoute
  HouseholdRoute: typeof HouseholdRoute
  InboxRoute: typeof InboxRoute
  ListsRoute: typeof ListsRoute
  LoyaltyRoute: typeof LoyaltyRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PantryRoute: typeof PantryRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RecipesRoute: typeof RecipesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StoreOnboardingRoute: typeof StoreOnboardingRoute
  StoresRoute: typeof StoresRoute
  VisionRoute: typeof VisionRoute
  ApiChatRoute: typeof ApiChatRoute
  JoinSlugRoute: typeof JoinSlugRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-onboarding': {
      id: '/store-onboarding'
      path: '/store-onboarding'
      fullPath: '/store-onboarding'
      preLoaderRoute: typeof StoreOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/household': {
      id: '/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof HouseholdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons': {
      id: '/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof CouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/recipes/$slug': {
      id: '/recipes/$slug'
      path: '/$slug'
      fullPath: '/recipes/$slug'
      preLoaderRoute: typeof RecipesSlugRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/portal/stores': {
      id: '/portal/stores'
      path: '/stores'
      fullPath: '/portal/stores'
      preLoaderRoute: typeof PortalStoresRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/rewards': {
      id: '/portal/rewards'
      path: '/rewards'
      fullPath: '/portal/rewards'
      preLoaderRoute: typeof PortalRewardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/promotions': {
      id: '/portal/promotions'
      path: '/promotions'
      fullPath: '/portal/promotions'
      preLoaderRoute: typeof PortalPromotionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/products': {
      id: '/portal/products'
      path: '/products'
      fullPath: '/portal/products'
      preLoaderRoute: typeof PortalProductsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/coupons': {
      id: '/portal/coupons'
      path: '/coupons'
      fullPath: '/portal/coupons'
      preLoaderRoute: typeof PortalCouponsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/campaigns': {
      id: '/portal/campaigns'
      path: '/campaigns'
      fullPath: '/portal/campaigns'
      preLoaderRoute: typeof PortalCampaignsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/join/$slug': {
      id: '/join/$slug'
      path: '/join/$slug'
      fullPath: '/join/$slug'
      preLoaderRoute: typeof JoinSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vault': {
      id: '/admin/vault'
      path: '/vault'
      fullPath: '/admin/vault'
      preLoaderRoute: typeof AdminVaultRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/taylor': {
      id: '/admin/taylor'
      path: '/taylor'
      fullPath: '/admin/taylor'
      preLoaderRoute: typeof AdminTaylorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organisations': {
      id: '/admin/organisations'
      path: '/organisations'
      fullPath: '/admin/organisations'
      preLoaderRoute: typeof AdminOrganisationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-usage': {
      id: '/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/stores/': {
      id: '/portal/stores/'
      path: '/'
      fullPath: '/portal/stores/'
      preLoaderRoute: typeof PortalStoresIndexRouteImport
      parentRoute: typeof PortalStoresRoute
    }
    '/portal/stores/$storeId': {
      id: '/portal/stores/$storeId'
      path: '/$storeId'
      fullPath: '/portal/stores/$storeId'
      preLoaderRoute: typeof PortalStoresStoreIdRouteImport
      parentRoute: typeof PortalStoresRoute
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminOrganisationsRoute: typeof AdminOrganisationsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminTaylorRoute: typeof AdminTaylorRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVaultRoute: typeof AdminVaultRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminOrganisationsRoute: AdminOrganisationsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminTaylorRoute: AdminTaylorRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVaultRoute: AdminVaultRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalStoresRouteChildren {
  PortalStoresStoreIdRoute: typeof PortalStoresStoreIdRoute
  PortalStoresIndexRoute: typeof PortalStoresIndexRoute
}

const PortalStoresRouteChildren: PortalStoresRouteChildren = {
  PortalStoresStoreIdRoute: PortalStoresStoreIdRoute,
  PortalStoresIndexRoute: PortalStoresIndexRoute,
}

const PortalStoresRouteWithChildren = PortalStoresRoute._addFileChildren(
  PortalStoresRouteChildren,
)

interface PortalRouteChildren {
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalCampaignsRoute: typeof PortalCampaignsRoute
  PortalCouponsRoute: typeof PortalCouponsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProductsRoute: typeof PortalProductsRoute
  PortalPromotionsRoute: typeof PortalPromotionsRoute
  PortalRewardsRoute: typeof PortalRewardsRoute
  PortalStoresRoute: typeof PortalStoresRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalCampaignsRoute: PortalCampaignsRoute,
  PortalCouponsRoute: PortalCouponsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProductsRoute: PortalProductsRoute,
  PortalPromotionsRoute: PortalPromotionsRoute,
  PortalRewardsRoute: PortalRewardsRoute,
  PortalStoresRoute: PortalStoresRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface RecipesRouteChildren {
  RecipesSlugRoute: typeof RecipesSlugRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesSlugRoute: RecipesSlugRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CouponsRoute: CouponsRoute,
  DealsRoute: DealsRoute,
  HouseholdRoute: HouseholdRoute,
  InboxRoute: InboxRoute,
  ListsRoute: ListsRoute,
  LoyaltyRoute: LoyaltyRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PantryRoute: PantryRoute,
  PortalRoute: PortalRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RecipesRoute: RecipesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StoreOnboardingRoute: StoreOnboardingRoute,
  StoresRoute: StoresRoute,
  VisionRoute: VisionRoute,
  ApiChatRoute: ApiChatRoute,
  JoinSlugRoute: JoinSlugRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
